paths:
  data: data
  static: public
  uploads: public/images
collections_config:
  data:
    path: data
    disable_add: true
    disable_add_folder: true
  posts:
    path: src/content/blog
    output: true
    url: '/blog/[slug]/'
    _enabled_editors:
      - content
      - visual
    add_options:
      - name: Add New Post
        schema: default
        icon: post_add
    schemas:
      default:
        name: New Post
        path: schemas/post.md
    _inputs:
      title:
        empty_type: string
      image:
        empty_type: string
      image_alt:
        empty_type: string
      author:
        empty_type: string
      tags:
        type: multiselect
        allow_create: true
        empty_type: array
  pages:
    path: src/content/pages
    url: '/[slug]/'
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
    filter:
      base: strict
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Blogging
    collections:
      - posts
  - heading: Data
    collections:
      - data
_inputs:
  button:
    options:
      preview:
        icon: smart_button
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: 'heading_text'
          - Heading
        subtext:
          - key: heading_color
          - 'Update heading and popover.'
  heading_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  heading_text:
    type: textarea
  subheading_text:
    type: textarea
  subheading_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  background_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  image_path:
    type: image
    options:
      paths:
        static: ''
        uploads: 'src/assets/images'
  flipped:
    type: switch
  layout:
    hidden: true
  date:
    instance_value: now
  title_suffix:
    comment: Added at the end of the title and highlighted in a different color
  page_size:
    type: number
    comment: The number of collection items to list per page
  social:
    options:
      preview:
        icon: link
  links:
    options:
      preview:
        icon: link
  items:
    options:
      preview:
        icon: link
  social[*].icon:
    type: select
    options:
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
  logo_url:
    comment: Link for the logo in the top left of the footer
  copyright:
    comment: Automatically prefixed with the current year
  seo:
    options:
      preview:
        icon: query_stats
        text:
          - 'Search engine optimization'
        subtext:
          - key: page_description
          - 'Update SEO values for the page'
  page_description:
    comment: Defaults to the description set in the Site SEO data file
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
  faivcon_image:
    type: image
    comment: For the icon meta tag
  canonical_url:
    comment: Defaults to the pages url
  featured_image:
    comment: Defaults to the image set in the Site SEO data file
  open_graph_type:
    comment: Defaults to the type 'website'
  author_twitter_handle:
    comment: Defaults to the twitter site value set in the Site SEO data file
  no_index:
    type: checkbox
    comment:
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
  button_icon:
    type: select
    options:
      values: data.icons
  button_link:
    type: url
  hover_brightness:
    type: range
    options:
      min: 0
      max: 1.5
      step: 0.05
  header_styles:
    options:
      preview:
        icon: menu
        text: Header Styles
        subtext: Set header colors per page

data_config:
  icons:
    path: data/icons.json
  colors:
    path: data/colors.json
  companies:
    path: data/companies.json

_structures:
  contact_details:
    values:
      - value:
          label:
          color:
          icon:
          text:
        _inputs:
          label:
            type: text
            comment: The label for the input.
          text:
            type: markdown
            options:
              bold: true
              format: p h1 h2 h3 h4
              italic: true
              link: true
              undo: true
              redo: true
              removeformat: true
              copyformatting: true
              bulletedlist: true
              numberedlist: true
              superscript: true
              subscript: true
              styles: /css/editor.css
  form:
    values:
      - value:
          label:
          color:
          name:
          type:
          radio_options:
        _inputs:
          label:
            type: text
            comment: The label for the input.
          name:
            type: text
            comment: The field name assigned to the data from this input. This will be used in the message you receive from the form submission.
          type:
            type: select
            comment: Selects the type of input.
            options:
              values:
                - text
                - textarea
                - radio
          radio_options:
            type: array
            options:
              structures: _structures.radio_option
        _structures:
          radio_option:
            values:
              - value:
                  label:
                  value:
                _inputs:
                  label:
                    type: text
                    comment: The label for the input.
                  value:
                    type: text
                    comment: The field name assigned to the data from this input. This will be used in the message you receive from the form submission.
  image:
    values:
      - value:
          image_path:
          image_alt:
  slide:
    values:
      - value:
          text:
