paths:
  data: data
  static: public
  uploads: public/images
collections_config:
  data:
    path: data
    disable_add: true
    disable_add_folder: true
    filter:
      base: all
      exclude:
        - icons.json
    _inputs:
      logo:
        type: image
      header:
        options:
          preview:
            text: Header Links
      footer:
        options:
          preview:
            text: Footer Information
      links:
        type: array
        options:
          structures: _structures.link
      social:
        type: array
        options:
          structures: _structures.social_link
      image:
        type: image
  pages:
    path: src/content/pages
    url: '/[slug]/'
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
    filter:
      base: strict
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Data
    collections:
      - data
file_config:
  - glob: data/colors.json
    _inputs:
      $:
        type: array
        comment: Set the colors available in the color selectors throughout the site.
      $[*]:
        options:
          preview:
            icon: palette
      value:
        type: color
      name:
        type: text
        comment: What is seen in the color selector dropdown.
  - glob: data/companies.json
    _inputs:
      $:
        type: array
        comment: Set the companies available in the company selectors throughout the site.
      $[*]:
        options:
          preview:
            icon: add_business
      coords:
        options:
          preview:
            icon: edit_location
            text: Coordinates
            metadata:
              - subtext:
                  - template: 'Coordinates {coords.lat}, {coords.lng}'
                  - Update company coordinates
  - glob: data/navigation.json
    _inputs:
      $:
        comment: Used to control the header and footer on the site.
  - glob: data/site.json
    _inputs:
      $:
        comment: Used to control the overall metadata and SEO information for the site.

_inputs:
  button:
    options:
      preview:
        icon: smart_button
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: 'heading_text'
          - Heading
        subtext:
          - key: heading_color
          - 'Update heading and popover.'
  heading_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  heading_text:
    type: textarea
  subheading_text:
    type: textarea
  subheading_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  background_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  image_path:
    type: image
    options:
      paths:
        static: ''
        uploads: 'src/assets/images'
  flipped:
    type: switch
  layout:
    hidden: true
  date:
    instance_value: now
  title_suffix:
    comment: Added at the end of the title and highlighted in a different color
  page_size:
    type: number
    comment: The number of collection items to list per page
  items:
    options:
      preview:
        icon: link
  logo_url:
    comment: Link for the logo in the top left of the footer
  copyright:
    comment: Automatically prefixed with the current year
  seo:
    options:
      preview:
        icon: query_stats
        text:
          - 'Search engine optimization'
        subtext:
          - key: page_description
          - 'Update SEO values for the page'
  page_description:
    comment: Defaults to the description set in the Site SEO data file
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
  faivcon_image:
    type: image
    comment: For the icon meta tag
  canonical_url:
    comment: Defaults to the pages url
  featured_image:
    comment: Defaults to the image set in the Site SEO data file
  open_graph_type:
    comment: Defaults to the type 'website'
  author_twitter_handle:
    comment: Defaults to the twitter site value set in the Site SEO data file
  no_index:
    type: checkbox
    comment:
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
  button_icon:
    type: select
    options:
      values: data.icons
  social_icon:
    type: select
    options:
      values: data.icons
  button_link:
    type: url
  hover_brightness:
    type: range
    options:
      min: 0
      max: 1.5
      step: 0.05
  header_styles:
    options:
      preview:
        icon: menu
        text: Header Styles
        subtext: Set header colors per page

data_config:
  icons:
    path: data/icons.json
  colors:
    path: data/colors.json
  companies:
    path: data/companies.json

_structures:
  link:
    values:
      - value:
          url:
          text:
        preview:
          icon: link
  social_link:
    values:
      - value:
          url:
          social_icon:
        preview:
          icon: group
  contact_details:
    values:
      - value:
          label:
          color:
          icon:
          text:
        preview:
          icon: call
          text:
            - key: label
            - Contact Detail
          subtext:
            - key: text
            - Update contact details.
        _inputs:
          label:
            type: text
            comment: The label for the input.
          text:
            type: markdown
            options:
              bold: true
              format: p h1 h2 h3 h4
              italic: true
              link: true
              undo: true
              redo: true
              removeformat: true
              copyformatting: true
              bulletedlist: true
              numberedlist: true
              superscript: true
              subscript: true
              styles: /css/editor.css
  form:
    values:
      - label: Form Input
        value:
          label:
          color:
          name:
          type:
          radio_options:
        preview:
          icon: check_box
          text:
            - key: label
            - Form Input
          subtext:
            - key: type
            - Update form input options.
        _inputs:
          label:
            type: text
            comment: The label for the input.
          name:
            type: text
            comment: The field name assigned to the data from this input. This will be used in the message you receive from the form submission.
          type:
            type: select
            comment: Selects the type of input.
            options:
              values:
                - text
                - textarea
                - radio
          radio_options:
            type: array
            comment: Used if the input type is 'radio'. This can be left empty if input type is 'text', or 'textarea'.
            options:
              structures: _structures.radio_option
        _structures:
          radio_option:
            values:
              - value:
                  label:
                  value:
                preview:
                  icon: check_box
                  text:
                    - key: label
                    - Radio Option
                  subtext:
                    - key: value
                    - Update radio option label and value.
                _inputs:
                  label:
                    type: text
                    comment: The label for the input.
                  value:
                    type: text
                    comment: The field name assigned to the data from this input. This will be used in the message you receive from the form submission.
  image:
    values:
      - value:
          image_path:
          image_alt:
        preview:
          icon: image
          text:
            - key: image_alt
            - Image
          subtext:
            - key: image_alt
            - Update image path and alt text.
  slide:
    values:
      - value:
          text:
        preview:
          icon: slideshow
          text: Slide
          subtext:
            - key: text
            - Update slide text.
