# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Error
  description: '404'
  icon: 'error'
  tags:
    - Error
    - '404'

# Defines the structure of this component, as well as the default values
blueprint:
  description: Could not find the page you were looking for.
  image_path: /src/assets/images/404.png
  image_alt: Error illustration
  button:
    button_text: Back Home
    button_icon:
    button_link: /
    background_color: '#2d2d2d'
    hover_brightness: 0.85
    text_color: '#ffffff'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
