# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Heading & Background Image
  icon: 'cottage'
  tags:
    - Hero
    - Image
    - Button

# Defines the structure of this component, as well as the default values
blueprint:
  title: Body of the Year
  subtitle: Sourdough Bakery - Dunedin, New Zealand
  image_path: /src/assets/images/flour-milling-hero.jpg
  image_alt: An image
  button:
    button_text: Contact us
    button_icon: CaretDown
    button_link: /#contact
    background_color: '#2d2d2d'
    hover_brightness: 0.85
    text_color: '#ffffff'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
