# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Locations Slider
  description: Locations slider
  icon: 'chrome_reader_mode'
  tags:
    - Slider
    - Locations
    - Left Right
    - Use with map

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: Loaves for sale
    heading_color: '#000000'
  subheading:
    subheading_text: Pick up a loaf from our core range to take home from these local legénds.
    subheading_color: '#000000'
  flipped: true
  show_description: false
  locations:
    - Maggies
    - The Duck
    - Vanguard Specialty Coffee

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  show_description:
    type: switch
  locations:
    type: multiselect
    comment: To be used in conjunction with the map component. Locations link to pins on the map. Add new locations via the [data file](cloudcannon:collections/data/companies.json).
    options:
      values: data.companies
      value_key: name
      preview:
        - key: name
