# Metadata about this component, to be used in the CMS
spec:
  structures:
    - cards
  label: Location Card
  description:
  icon: 'style'
  tags:
    - Card
    - Location

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ''
  text: ''
  image:
    src: ''
    alt: ''
  link: ''

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
