# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Image Gallery
  description: Full screen slidable image gallery
  icon: 'image'
  tags:
    - Images
    - Gallery

# Defines the structure of this component, as well as the default values
blueprint:
  images:
    - image_path:
      image_alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  images:
    type: array
    comment: Gallery slider will only display the first image in the visual editor. Drag an image to the top to see it on the page, and drag it back into order once finished.
    structures: _structures.image
    options:
      preview:
        icon: image
