# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Form
  description: Contact Form
  icon: 'form'
  tags: ['form']

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: Contact Us
    heading_color: '#ffffff'
  subheading:
    subheading_text: Get in touch to order bread, enquire about wholesale, or ask us a question!
    subheading_color: '#ffffff'
  contact_details:
    - label: Address
      icon: LocationPin
      text: >-
        [123 Bakery Street](/where/#map)
    - label: Email
      icon: Envelope
      text: botybakery@gmail.com
  form:
    form_fields:
      - label: Email Address
        name: email
        type: text
        options: []
      - label: Name
        name: name
        type: text
        options: []
      - label: Message
        name: message
        type: textarea
        options: []
      - label: Type of Enquiry
        name: subject
        type: radio
        options:
          - label: General
            value: General Enquiry
          - label: Wholesale
            value: Wholesale Enquiry

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
    options:
      bold: true
      format: p h1 h2 h3 h4
      italic: true
      link: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      bulletedlist: true
      numberedlist: true
      superscript: true
      subscript: true
      styles: /css/editor.css
