# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Card Grid
  description: Card Grid section
  icon: 'grid'
  tags: ['block', 'grid']

# Defines the structure of this component, as well as the default values
blueprint:
  type: icons
  cards:
    - heading:
      text:
      link:
      image:
      icon:
      background_color:
      background_image:
      column_span: 1

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  icon:
    type: select
    values: data.icons
    hidden: 'image'
  type:
    type: select
    label: Card type
    options:
      values:
        - icons
        - images
  image:
    hidden: 'icon'
  background_color:
    type: color
    hidden: 'background_image'
  background_image:
    type: image
    comment: Leave this blank to enable a background color control.
  column_span:
    type: select
    label: Column span
    options:
      values:
        - 1
        - 2
        - 3
