# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Slider
  description: Plain text slider
  icon: 'chrome_reader_mode'
  tags:
    - Slider
    - Text
    - Left Right

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: A rotating range of specialty loaves
    heading_color: '#000000'
  subheading:
    subheading_text: We sell our core menu and a changing range of specialty loaves, which can be purchased to take home from Taste Nature.
    subheading_color: '#000000'
  flipped: false
  slides:
    - text: >-
        ### Saturday


        - Wheat


        - Olive and Rosemary


        - Oat Porridge


        - Ciabatta
    - text: >-
        ### Tuesday


        - Organic Yeasted Variety ( All Tin Loafs )


        - Soft White Loaf 


        - Purple Wheat Loaf


        - Multigrain Loaf

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  slides:
    type: array
    structures: _structures.slide
  slides[*]:
    type: markdown
    options:
      bold: true
      format: p h1 h2 h3 h4
      italic: true
      link: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      bulletedlist: true
      numberedlist: true
      blockquote: true
      superscript: true
      subscript: true
      horizontalrule: true
      image: true
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      styles: /css/editor.css
      preview:
        icon: slideshow
        text: Slide
        subtext:
          - key: text
          - Update slide text
