# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Slider
  description: Left Right block
  icon: 'chrome_reader_mode'
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Specialty Loaf Menu
  subheading: Our rotating menu of specialty breads, found at Taste Nature.
  slides:
    - text: >-
        ### Saturday


        - Wheat


        - Olive and Rosemary


        - Oat Porridge


        - Ciabatta
    - text: >-
        ### Tuesday


        - Organic Yeasted Variety ( All Tin Loafs )


        - Soft White Loaf 


        - Purple Wheat Loaf


        - Multigrain Loaf

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
